#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ordersystem.Droid.Resource", IsApplication=true)]

namespace Ordersystem.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_custom_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int theme_devicedefault_background = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ExpandArrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Forward = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int editText1 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int errorMsg = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int imageView1 = 2131165192;
			
			// aapt resource value: 0x7f07004d
			public const int imageView10 = 2131165261;
			
			// aapt resource value: 0x7f07004a
			public const int imageView11 = 2131165258;
			
			// aapt resource value: 0x7f070047
			public const int imageView12 = 2131165255;
			
			// aapt resource value: 0x7f070044
			public const int imageView13 = 2131165252;
			
			// aapt resource value: 0x7f070041
			public const int imageView14 = 2131165249;
			
			// aapt resource value: 0x7f07003e
			public const int imageView15 = 2131165246;
			
			// aapt resource value: 0x7f07003b
			public const int imageView16 = 2131165243;
			
			// aapt resource value: 0x7f070038
			public const int imageView17 = 2131165240;
			
			// aapt resource value: 0x7f070035
			public const int imageView18 = 2131165237;
			
			// aapt resource value: 0x7f070032
			public const int imageView19 = 2131165234;
			
			// aapt resource value: 0x7f07000b
			public const int imageView2 = 2131165195;
			
			// aapt resource value: 0x7f07002f
			public const int imageView20 = 2131165231;
			
			// aapt resource value: 0x7f07002c
			public const int imageView21 = 2131165228;
			
			// aapt resource value: 0x7f070029
			public const int imageView22 = 2131165225;
			
			// aapt resource value: 0x7f070026
			public const int imageView23 = 2131165222;
			
			// aapt resource value: 0x7f070023
			public const int imageView24 = 2131165219;
			
			// aapt resource value: 0x7f070020
			public const int imageView25 = 2131165216;
			
			// aapt resource value: 0x7f07001d
			public const int imageView26 = 2131165213;
			
			// aapt resource value: 0x7f07001a
			public const int imageView27 = 2131165210;
			
			// aapt resource value: 0x7f070017
			public const int imageView28 = 2131165207;
			
			// aapt resource value: 0x7f070014
			public const int imageView29 = 2131165204;
			
			// aapt resource value: 0x7f070062
			public const int imageView3 = 2131165282;
			
			// aapt resource value: 0x7f070011
			public const int imageView30 = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int imageView31 = 2131165198;
			
			// aapt resource value: 0x7f07005f
			public const int imageView4 = 2131165279;
			
			// aapt resource value: 0x7f07005c
			public const int imageView5 = 2131165276;
			
			// aapt resource value: 0x7f070059
			public const int imageView6 = 2131165273;
			
			// aapt resource value: 0x7f070056
			public const int imageView7 = 2131165270;
			
			// aapt resource value: 0x7f070053
			public const int imageView8 = 2131165267;
			
			// aapt resource value: 0x7f070050
			public const int imageView9 = 2131165264;
			
			// aapt resource value: 0x7f070002
			public const int myButton = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int row1 = 2131165190;
			
			// aapt resource value: 0x7f070021
			public const int row10 = 2131165217;
			
			// aapt resource value: 0x7f070024
			public const int row11 = 2131165220;
			
			// aapt resource value: 0x7f070027
			public const int row12 = 2131165223;
			
			// aapt resource value: 0x7f07002a
			public const int row13 = 2131165226;
			
			// aapt resource value: 0x7f07002d
			public const int row14 = 2131165229;
			
			// aapt resource value: 0x7f070030
			public const int row15 = 2131165232;
			
			// aapt resource value: 0x7f070033
			public const int row16 = 2131165235;
			
			// aapt resource value: 0x7f070036
			public const int row17 = 2131165238;
			
			// aapt resource value: 0x7f070039
			public const int row18 = 2131165241;
			
			// aapt resource value: 0x7f07003c
			public const int row19 = 2131165244;
			
			// aapt resource value: 0x7f070009
			public const int row2 = 2131165193;
			
			// aapt resource value: 0x7f07003f
			public const int row20 = 2131165247;
			
			// aapt resource value: 0x7f070042
			public const int row21 = 2131165250;
			
			// aapt resource value: 0x7f070045
			public const int row22 = 2131165253;
			
			// aapt resource value: 0x7f070048
			public const int row23 = 2131165256;
			
			// aapt resource value: 0x7f07004b
			public const int row24 = 2131165259;
			
			// aapt resource value: 0x7f07004e
			public const int row25 = 2131165262;
			
			// aapt resource value: 0x7f070051
			public const int row26 = 2131165265;
			
			// aapt resource value: 0x7f070054
			public const int row27 = 2131165268;
			
			// aapt resource value: 0x7f070057
			public const int row28 = 2131165271;
			
			// aapt resource value: 0x7f07005a
			public const int row29 = 2131165274;
			
			// aapt resource value: 0x7f07000c
			public const int row3 = 2131165196;
			
			// aapt resource value: 0x7f07005d
			public const int row30 = 2131165277;
			
			// aapt resource value: 0x7f070060
			public const int row31 = 2131165280;
			
			// aapt resource value: 0x7f07000f
			public const int row4 = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int row5 = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int row6 = 2131165205;
			
			// aapt resource value: 0x7f070018
			public const int row7 = 2131165208;
			
			// aapt resource value: 0x7f07001b
			public const int row8 = 2131165211;
			
			// aapt resource value: 0x7f07001e
			public const int row9 = 2131165214;
			
			// aapt resource value: 0x7f070007
			public const int row_name1 = 2131165191;
			
			// aapt resource value: 0x7f070022
			public const int row_name10 = 2131165218;
			
			// aapt resource value: 0x7f070025
			public const int row_name11 = 2131165221;
			
			// aapt resource value: 0x7f070028
			public const int row_name12 = 2131165224;
			
			// aapt resource value: 0x7f07002b
			public const int row_name13 = 2131165227;
			
			// aapt resource value: 0x7f07002e
			public const int row_name14 = 2131165230;
			
			// aapt resource value: 0x7f070031
			public const int row_name15 = 2131165233;
			
			// aapt resource value: 0x7f070034
			public const int row_name16 = 2131165236;
			
			// aapt resource value: 0x7f070037
			public const int row_name17 = 2131165239;
			
			// aapt resource value: 0x7f07003a
			public const int row_name18 = 2131165242;
			
			// aapt resource value: 0x7f07003d
			public const int row_name19 = 2131165245;
			
			// aapt resource value: 0x7f07000a
			public const int row_name2 = 2131165194;
			
			// aapt resource value: 0x7f070040
			public const int row_name20 = 2131165248;
			
			// aapt resource value: 0x7f070043
			public const int row_name21 = 2131165251;
			
			// aapt resource value: 0x7f070046
			public const int row_name22 = 2131165254;
			
			// aapt resource value: 0x7f070049
			public const int row_name23 = 2131165257;
			
			// aapt resource value: 0x7f07004c
			public const int row_name24 = 2131165260;
			
			// aapt resource value: 0x7f07004f
			public const int row_name25 = 2131165263;
			
			// aapt resource value: 0x7f070052
			public const int row_name26 = 2131165266;
			
			// aapt resource value: 0x7f070055
			public const int row_name27 = 2131165269;
			
			// aapt resource value: 0x7f070058
			public const int row_name28 = 2131165272;
			
			// aapt resource value: 0x7f07005b
			public const int row_name29 = 2131165275;
			
			// aapt resource value: 0x7f07000d
			public const int row_name3 = 2131165197;
			
			// aapt resource value: 0x7f07005e
			public const int row_name30 = 2131165278;
			
			// aapt resource value: 0x7f070061
			public const int row_name31 = 2131165281;
			
			// aapt resource value: 0x7f070010
			public const int row_name4 = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int row_name5 = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int row_name6 = 2131165206;
			
			// aapt resource value: 0x7f070019
			public const int row_name7 = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int row_name8 = 2131165212;
			
			// aapt resource value: 0x7f07001f
			public const int row_name9 = 2131165215;
			
			// aapt resource value: 0x7f070004
			public const int scrollView1 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int tableLayout1 = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int titelText = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Log_In = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main_Window = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
